export const GLOSSARY: Record<string, [string, string]> = {
  SetupSprite: ["SetupSprite", "Pops 7 values (step pointer first, then sprite index, follow index, X, Y, rate, flags) and starts a sprite in that slot with a fresh position, speed and step pointer. Index -1 takes the first free slot."],
  RemoveSprite: ["RemoveSprite", "Pops a sprite index and deactivates that slot. Its last image is erased on the next frame."],
  WaitForFrames: ["WaitForFrames", "Pops a frame count and pauses the instruction VM for exactly that many frames while sprites keep stepping. 0 does nothing; negative values wrap and wait about 65536 frames."],
  TriggerAudio: ["TriggerAudio", "Pops an index into the game's audio table and queues that sound for the end of the frame. The viewer only reports the index."],
  StampSprite: ["StampSprite", "Pops a sprite index. At the end of this frame the sprite is drawn into the background page instead of the draw page, so it stays behind permanently."],
  Push: ["Push", "Pushes a signed 16-bit literal onto the VM stack, or the value of a register when written as Rn. Retail files push every argument right before the instruction that consumes it."],
  PopToRegister: ["PopToRegister", "Pops the top of the stack into a register. Registers outside 0 to 50 discard the value; retail files use R-1 to throw a value away."],
  Dup: ["Dup", "Duplicates the top stack value."],
  CompareEqual: ["CompareEqual", "Pops two values and pushes 1 if they are equal, otherwise 0."],
  CompareNotEqual: ["CompareNotEqual", "Pops two values and pushes 1 if they differ, otherwise 0."],
  CompareGreaterThan: ["CompareGreaterThan", "Pops two values and pushes 1 if the first pushed is greater than the second, otherwise 0."],
  CompareLessThan: ["CompareLessThan", "Pops two values and pushes 1 if the first pushed is less than the second, otherwise 0."],
  CompareGreaterOrEqual: ["CompareGreaterOrEqual", "Pops two values and pushes 1 if the first pushed is greater than or equal to the second, otherwise 0."],
  CompareLessOrEqual: ["CompareLessOrEqual", "Pops two values and pushes 1 if the first pushed is less than or equal to the second, otherwise 0."],
  Add: ["Add", "Pops two values and pushes their sum. Arithmetic is 16-bit and wraps."],
  Subtract: ["Subtract", "Pops two values and pushes first minus second, wrapping at 16 bits."],
  Multiply: ["Multiply", "Pops two values and pushes their product, wrapping at 16 bits."],
  Divide: ["Divide", "Pops two values and pushes first divided by second. Division by zero crashes the game; the viewer pushes 0 and warns."],
  JumpIf: ["JumpIf", "Pops a value and jumps to the given byte offset in the data section when it is non-zero."],
  Jump: ["Jump", "Jumps unconditionally to the given byte offset in the data section."],
  End: ["End", "Stops the instruction VM for good. Later frames only step and draw sprites until the game stops the animation."],
  EndImmediate: ["EndImmediate", "Ends the animation immediately; the current frame is not stepped or drawn. The viewer's slider stops here."],
  Return: ["Return", "Pops an address and jumps to it. Unused by retail files."],
  Call: ["Call", "Pushes the address of the next instruction and jumps to the target. Unused by retail files."],

  DrawFrame: ["DrawFrame", "Sets the image the sprite shows from now on (255 hides it) and ends the sprite's turn for this frame. It is the only step that ends a frame."],
  MoveAbsolute: ["MoveAbsolute", "Sets the sprite's position, or its offset when it follows another sprite."],
  MoveRelative: ["MoveRelative", "Adds the given amounts to the sprite's position or follow offset."],
  SetSpeed: ["SetSpeed", "Sets the sprite's speed, the amount added to its credit every frame."],
  AddSpeed: ["AddSpeed", "Adds the value to the sprite's speed."],
  PushCounter: ["PushCounter", "Pushes a loop counter onto the sprite's counter stack (10 deep)."],
  JumpIfCounter: ["JumpIfCounter", "Decrements the top counter. If it is still non-zero, jumps to the target; otherwise pops it and continues. A counter of N runs the loop body N times."],
  Restart: ["Restart", "Resets the sprite to its first step, original position and rate, clears its counters, and keeps stepping."],
  Loop: ["Loop", "Resets the sprite to its first step and clears its counters, keeping its position and speed."],
  Pause: ["Pause", "Stops stepping but keeps drawing the last image. The sprite stays visible but frozen."],
  Stop: ["Stop", "Stops stepping and drawing. The sprite becomes inactive."],

  offset: ["Offset", "Byte offset within the data section. Jumps and step pointers use these absolute offsets. Highlighted offsets are jump targets or sequence starts."],
  bytes: ["Bytes", "The raw encoded bytes of this entry."],
  instruction: ["Instruction", "The decoded opcode. The yellow row is where the instruction pointer sits; green rows ran during the current frame."],
  operand: ["Operand", "The literal, register or target encoded inside the instruction, if any. Targets are clickable."],
  folded: ["Folded arguments", "For instructions that pop values, the literal pushes right before them, shown as the arguments they will receive."],
  step: ["Step", "The decoded step type. Yellow rows are where active sprites currently point; green rows ran this frame for the selected sprite."],
  sequence: ["Sequence", "Marks the first step of a sequence and which sprites are set up to start there."],
  spritesHere: ["Sprites here", "Active sprites whose step pointer is at this step right now."],

  slot: ["Slot", "Sprite slot number, 1 to 50. Sprites draw in slot order, so higher slots appear on top."],
  active: ["Active", "Whether the slot is currently running. Inactive sprites are not stepped or drawn."],
  image: ["Image", "The image ID the sprite is showing, from its last DrawFrame, with its size."],
  position: ["Position", "Where the sprite is drawn, including any followed sprite's position. Undefined when the followed slot is inactive."],
  ownPos: ["Own pos", "The sprite's own coordinates, or its offset when it follows another sprite."],
  follow: ["Follow", "The slot this sprite follows. It is drawn at that sprite's position plus its own setup position and offset."],
  stepPtr: ["Step", "Byte offset of the next step this sprite will run."],
  speed: ["Speed", "Added to the credit every frame. 255 steps every frame, 128 about every other frame, 0 never."],
  credit: ["Credit", "Accumulated speed. When it passes 255 the sprite runs steps until one ends the frame, and 255 is deducted."],
  rate: ["Rate", "The speed given at setup, restored by Restart."],
  flags: ["Flags", "Non-zero draws the sprite without erase tracking, so it is never cleared on later frames. Retail files use it for static pieces."],
  counters: ["Counters", "The sprite's loop counter stack, bottom first."],
  stepsThisFrame: ["Steps this frame", "Offsets of the steps this sprite ran during the current frame."],

  imageId: ["ID", "Image ID used by DrawFrame steps, 0 to 249. Gaps in the table are unused IDs."],
  imageIndex: ["Index", "Position of the image within the file, in the order stored."],
  imageSize: ["Size", "Image width and height in pixels."],
  imageOffset: ["Offset", "File offset where the image data starts."],
  imageExtra: ["Extra", "The u16 stored with the table entry. It has no effect on playback and is probably authoring metadata."],

  reg: ["Register", "The VM register to write. Files read registers with Push Rn and write them with PopToRegister."],
  regValue: ["Value", "The value written into the register, as a signed 16-bit number."],
  regFrame: ["Frame", "The frame at whose start the value is written. Frame 0 sets it before any instruction runs, which is how the game passes values in."],
  regNow: ["Apply now", "Sets the frame to the current frame, so the value takes effect from here on."],
  addRegister: ["Add register", "Adds a row for any register 0 to 50, even one the file does not reference."],
  clearInputs: ["Clear all", "Removes every register input and replays from frame 0."],

  file: ["Open .PAN", "Load a PAN file from your machine. Nothing is uploaded; parsing and playback run in the browser. Dropping a file anywhere on the page also works."],
  help: ["Help", "Opens the reference on the PAN format and the viewer."],
  demo: ["Load demo", "Opens a small animation that ships with the viewer. It was made for the viewer, not taken from the game, and exercises registers, loops, following and stamping."],
  tour: ["Tour", "Walks through loading a file, the player controls and the register inputs."],
  rewind: ["Rewind", "Back to frame 0. Keyboard: Home."],
  back: ["Previous frame", "Step one frame back. Keyboard: Left arrow."],
  play: ["Play / pause", "Plays at the file's frame delay times the speed setting. Keyboard: Space."],
  forward: ["Next frame", "Step one frame forward. Keyboard: Right arrow."],
  scrub: ["Frame slider", "Drag to any frame. Every frame is recomputed from frame 0, so seeking backwards is exact."],
  speedSelect: ["Speed", "Multiplier on the file's frame delay. 1x is the speed the game plays it at, 18.2 timer ticks per second."],
  zoom: ["Zoom", "Pixel scale of the screen. Fit picks the largest whole-ish scale for the space available."],
  maxFrames: ["Frames", "How many frames the slider covers. Animations that end with End run their sprites forever, so this is a viewing limit."],
  transparent: ["Colour 0 transparent", "Shows colour index 0 as the checkerboard instead of black, to reveal unpainted areas of the pages."],
  export: ["Export WebM", "Records a frame range as a WebM video at the file's frame rate, using the current register inputs."],
  status: ["Status", "Instruction pointer, remaining wait, whether the VM has ended, audio triggered this frame and the active sprite count."],
  screen: ["Screen", "The draw page as the game would show it: background page plus every visible sprite, through the file's colour block."],

  tabInfo: ["Info", "Header fields, colour block and the image table."],
  tabImages: ["Images", "Every embedded image, shown through the file's colour mapping."],
  tabInstructions: ["Instructions", "The reachable instruction listing with the instruction pointer and this frame's executed rows highlighted."],
  tabSteps: ["Steps", "The reachable step listing. Sprite numbers mark where each active sprite currently points."],
  tabSprites: ["Sprites", "Live state of every slot that has been set up. Click a row to outline that sprite on the screen."],
  tabState: ["VM state", "Instruction pointer, wait counter, stack, registers and audio for the current frame."],
  tabWarnings: ["Warnings", "Anything unusual the parser or simulation ran into."],

  vmFrame: ["Frame", "The frame currently shown, counted from 0."],
  vmIp: ["Instruction pointer", "Byte offset of the next instruction the VM will run. After End it stays put."],
  vmWaiting: ["Waiting", "Whether a WaitForFrames is in progress and how many frames remain."],
  vmEnded: ["Animation ended", "Set when EndImmediate ran. No further frames are stepped or drawn."],
  vmStack: ["Stack", "The 16-bit value stack, bottom first. Retail files leave it empty between instructions."],
  vmAudio: ["Audio this frame", "Audio table indices triggered this frame, most recent first."],
  vmInstructions: ["Instructions this frame", "Offsets of every instruction the VM executed during this frame."],
  vmRegisters: ["Registers", "All 51 registers. Highlighted ones hold a non-zero value."],

  infoFile: ["File", "File name and size in bytes."],
  infoSize: ["Size", "Bounding width and height of the animation, from the header."],
  infoPosition: ["Position", "Default screen position in the header. The game passes its own position, so this is unused."],
  infoDelay: ["Frame delay", "Minimum timer ticks per frame, at 18.2 ticks per second."],
  infoBackground: ["Background", "How the background page starts: the previous animation's page, the first image, or a solid colour."],
  infoFormat: ["Image format", "Compressed is the shared LZW format used by every retail file; raw stores one byte per pixel."],
  infoImages: ["Images", "Number of images in the index table, plus the separate background image if present."],
  infoData: ["Data section", "The block holding instructions and steps. Its size is declared in 16-byte units."],
  infoInstructions: ["Instructions", "Instructions reachable from offset 0 by following jumps."],
  infoSteps: ["Steps", "Steps reachable from the step pointers that SetupSprite instructions push."],
  infoRegisters: ["Registers used", "Registers the file reads or writes. Register inputs for these appear in the panel."],
  colourBlock: ["Colour block", "Maps each colour index to one of the 16 VGA colours while the animation plays. Entry 0 always shows black."],
};
